name: selam_core
description: "selam_core inventary managment."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.11
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.5.0
  build_runner: ^2.1.0

flutter:
  uses-material-design: true
